### ISSUE TITLE
Exceedance Plot Axes are reversed

### ISSUE THREAD

**Issue by rma-tom** [CentralValleyModeling/callite-report-tool#6]
In the revised version of the CalLite report, the axes of the exceedance plots are reversed relative to the original version. This probably happened when refactoring in a new version of jfreechart.

**Comment by hxiedwr** [comment]
Good to know. Thank you.



________________________________
From: Tom Evans ***@***.***>
Sent: Wednesday, March 27, 2024 3:42 PM
To: CentralValleyModeling/callite-report-tool ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CentralValleyModeling/callite-report-tool] Exceedance Plot Axes are reversed (Issue #6)


In the revised version of the CalLite report, the axes of the exceedance plots are reversed relative to the original version. This probably happened when refactoring in a new version of jfreechart.

**Comment by rma-tom** [comment]
Change made. Hao approved merge to main branch.
